// react-client/src/components/Forecast/BusStopSelector.js
import { getDistanceFromLatLonInKm } from "../../utilities/utils";

function BusStopSelector({ stops, selectStop, selectedStop, isLoading, userLocation }) {
    return (
    <>
        <hr />
        <div className='row justify-content-center mb-3'>
            <div className='col text-center'>
                <h5>Select Bus Stop:</h5>
                <div className='list-group overflow-scroll mx-auto col-md-3'
                style={{'maxHeight': '300px'}}>
                    {stops.map((stop) => {
                        const isSelected = stop.stopSequence === selectedStop
                        const showSpinner = isSelected && isLoading
                        let distanceDisplay = "";
                        let stopNameWidth = "100%";

                        // If userLocation is provided, calculate and display the distance
                        if (userLocation && userLocation.latitude && userLocation.longitude) {
                            const distance = getDistanceFromLatLonInKm(
                                userLocation.latitude,
                                userLocation.longitude,
                                stop.latitude,
                                stop.longitude
                            );
                            distanceDisplay = ` (${distance.toFixed(1)} km)`;
                            stopNameWidth = "70%";
                        }
                        
                        return (
                            <button
                            key={stop.stopSequence}
                            onClick={() => selectStop(stop.stopSequence)}
                            className={`list-group-item ${isSelected ? 'active disabled' : ''} list-group-item-action text-center`}>
                                <div style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
                                    <div style={{width: stopNameWidth, textAlign: "center"}}>
                                        {stop.name}
                                        { showSpinner && <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> } 
                                    </div>
                                    <div style={{ color: 'grey' }}>{distanceDisplay}</div>
                                </div>
                            </button>
                        )
                    })}
                </div>
            </div>
        </div>
    </>
    )
}

export default BusStopSelector

// client/src/components/BusStopSelector.vue
<template>
    <hr />
    <div class="row justify-content-center">
      <div class="col text-center">
        <h5>Select Bus Stop:</h5>
        <div class="list-group" style="max-height: 300px; overflow-y: auto; width: 300px; margin: 0 auto;">
          <button
            v-for="stop in selectedDirectionStops"
            :key="stop.stopSequence"
            class="list-group-item list-group-item-action text-center"
            @click="emitStop(stop.stopSequence)"
          >
            {{ stop.name }}
          </button>
        </div>
      </div>
    </div>
</template>

<script>
export default {
  props: {
    selectedDirectionStops: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
        selectedStop: ''
    };
  },
  methods: {
    emitStop(stopSequence) {
        this.selectedStop = stopSequence;
        this.$emit('stop', stopSequence);
    }
  }
}
</script>
