// react-client/src/components/DirectionSelector.js
function DirectionSelector({ directions, onClick, selectedDirection }) {
    return (
    <>
        <hr />
        <div className='row justify-content-center'>
            <div className='col text-center'>
                <h5>Select Direction:</h5>
                <div className='btn-group' role='group'>
                    {Object.entries(directions).map(([key, direction]) => (
                        <button
                        key={key}
                        className={`btn btn-primary${selectedDirection === key ? ' active' : ''}`}
                        onClick={() => onClick(key)}
                        >
                            {direction}
                        </button>
                    ))}
                </div>
            </div>
        </div>
    </>
    )
}

export default DirectionSelector

// client/src/components/DirectionSelector.vue
<template>
    <hr />
    <div class="row justify-content-center">
      <div class="col text-center">
        <h5>Select Direction:</h5>
        <div class="btn-group" role="group">
          <button
            v-for="(direction, index) in directions"
            :key="index"
            class="btn"
            :class="[
              'btn-primary',
              selectedDirection === direction ? 'active' : '',
            ]"
            @click="emitDirection(index)"
          >
            {{ direction }}
          </button>
        </div>
      </div>
    </div>
</template>

<script>
export default {
  props: {
    directions: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
        selectedDirection: ''
    };
  },
  methods: {
    emitDirection(index) {
        this.selectedDirection = this.directions[index];
        this.$emit('direction', index);
    }
  }
};
</script>
