// react-client/src/components/ErrorMessage.js
function ErrorMessage({ message }) {
    return (
        <div className='row justify-content-center'>
            <div className='col-auto'>
                <div className='alert alert-danger' role='alert'>
                { message }
                </div>
            </div>
        </div>
    )
}

export default ErrorMessage

// client/src/components/ErrorMessage.vue
<template>
    <div class="row justify-content-center">
      <div class="col-auto">
        <div class="alert alert-danger" role="alert">
          {{ message }}
        </div>
      </div>
    </div>
</template>

<script>
export default {
  props: {
    message: {
      type: String,
      required: true,
    },
  },
};
</script>
